export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export  const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const CART_RESET = "CART_RESET";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAIL";

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAIL = "DELETE_CART_FAIL";

export const ADD_TO_UNAUTHORIZED_CART = "ADD_TO_UNAUTHORIZED_CART";
export const REMOVE_FROM_UNAUTHORIZED_CART = "REMOVE_FROM_UNAUTHORIZED_CART";
export const ADD_TO_UNAUTHORIZED_CART_REQUEST = "ADD_TO_UNAUTHORIZED_CART_REQUEST";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";