export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST";
export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS";
export const ALL_CATEGORY_FAIL = "ALL_CATEGORY_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCTS_REQUEST";
export const ADMIN_PRODUCTS_SUCCESS = "ADMIN_PRODUCTS_SUCCESS";
export const ADMIN_PRODUCTS_FAIL = "ADMIN_PRODUCTS_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const ALL_REVIEWS_REQUEST = "ALL_REVIEWS_REQUEST";
export const ALL_REVIEWS_SUCCESS = "ALL_REVIEWS_SUCCESS";
export const ALL_REVIEWS_FAIL = "ALL_REVIEWS_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const SLIDER_PRODUCTS_REQUEST = "SLIDER_PRODUCTS_REQUEST";
export const SLIDER_PRODUCTS_SUCCESS = "SLIDER_PRODUCTS_SUCCESS";
export const SLIDER_PRODUCTS_FAIL = "SLIDER_PRODUCTS_FAIL";

export const VARIANT_DETAILS_REQUEST = "VARIANT_DETAILS_REQUEST";
export const VARIANT_DETAILS_SUCCESS = "VARIANT_DETAILS_SUCCESS";
export const VARIANT_DETAILS_FAIL = "VARIANT_DETAILS_FAIL";

export const ADMIN_VARIANTS_REQUEST = "ADMIN_VARIANTS_REQUEST";
export const ADMIN_VARIANTS_SUCCESS = "ADMIN_VARIANTS_SUCCESS";
export const ADMIN_VARIANTS_FAIL = "ADMIN_VARIANTS_FAIL";

export const ADMIN_CATEGORY_REQUEST = "ADMIN_CATEGORY_REQUEST";
export const ADMIN_CATEGORY_SUCCESS = "ADMIN_CATEGORY_SUCCESS";
export const ADMIN_CATEGORY_FAIL = "ADMIN_CATEGORY_FAIL";

export const ADMIN_CATEGORY_DETAIL_REQUEST = "ADMIN_CATEGORY_DETAIL_REQUEST";
export const ADMIN_CATEGORY_DETAIL_SUCCESS = "ADMIN_CATEGORY_DETAIL_SUCCESS";
export const ADMIN_CATEGORY_DETAIL_FAIL = "ADMIN_CATEGORY_DETAIL_FAIL";

export const ADMIN_VARIANT_DETAIL_REQUEST = "ADMIN_VARIANT_DETAIL_REQUEST";
export const ADMIN_VARIANT_DETAIL_SUCCESS = "ADMIN_VARIANT_DETAIL_SUCCESS";
export const ADMIN_VARIANT_DETAIL_FAIL = "ADMIN_VARIANT_DETAIL_FAIL";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";

export const NEW_CATEGORY_REQUEST = "NEW_CATEGORY_REQUEST";
export const NEW_CATEGORY_SUCCESS = "NEW_CATEGORY_SUCCESS";
export const NEW_CATEGORY_FAIL = "NEW_CATEGORY_FAIL";
export const NEW_CATEGORY_RESET = "NEW_CATEGORY_RESET";

export const ADMIN_PRODUCT_VARIANT_REQUEST = "ADMIN_PRODUCT_VARIANT_REQUEST";
export const ADMIN_PRODUCT_VARIANT_SUCCESS = "ADMIN_PRODUCT_VARIANT_SUCCESS";
export const ADMIN_PRODUCT_VARIANT_FAIL = "ADMIN_PRODUCT_VARIANT_FAIL";

export const ADMIN_COLORS_REQUEST = "ADMIN_COLORS_REQUEST";
export const ADMIN_COLORS_SUCCESS = "ADMIN_COLORS_SUCCESS";
export const ADMIN_COLORS_FAIL = "ADMIN_COLORS_FAIL";

export const ADMIN_SIZES_REQUEST = "ADMIN_SIZES_REQUEST";
export const ADMIN_SIZES_SUCCESS = "ADMIN_SIZES_SUCCESS";
export const ADMIN_SIZES_FAIL = "ADMIN_SIZES_FAIL";

export const ADMIN_THICKNESS_REQUEST = "ADMIN_THICKNESS_REQUEST";
export const ADMIN_THICKNESS_SUCCESS = "ADMIN_THICKNESS_SUCCESS";
export const ADMIN_THICKNESS_FAIL = "ADMIN_THICKNESS_FAIL";

export const ADMIN_SUBCATEGORY_REQUEST = "ADMIN_SUBCATEGORY_REQUEST";
export const ADMIN_SUBCATEGORY_SUCCESS = "ADMIN_SUBCATEGORY_SUCCESS";
export const ADMIN_SUBCATEGORY_FAIL = "ADMIN_SUBCATEGORY_FAIL";

export const UPDATE_VARIANT_REQUEST = "UPDATE_VARIANT_REQUEST";
export const UPDATE_VARIANT_SUCCESS = "UPDATE_VARIANT_SUCCESS";
export const UPDATE_VARIANT_FAIL = "UPDATE_VARIANT_FAIL";
export const UPDATE_VARIANT_RESET = "UPDATE_VARIANT_RESET";

export const NEW_VARIANT_REQUEST = "NEW_VARIANT_REQUEST";
export const NEW_VARIANT_SUCCESS = "NEW_VARIANT_SUCCESS";
export const NEW_VARIANT_FAIL = "NEW_VARIANT_FAIL";
export const NEW_VARIANT_RESET = "NEW_VARIANT_RESET";

export const DELETE_VARIANT_REQUEST = "DELETE_VARIANT_REQUEST";
export const DELETE_VARIANT_SUCCESS = "DELETE_VARIANT_SUCCESS";
export const DELETE_VARIANT_FAIL = "DELETE_VARIANT_FAIL";
export const DELETE_VARIANT_RESET = "DELETE_VARIANT_RESET";

export const WARNING_STOCK_REQUEST = "WARNING_STOCK_REQUEST";
export const WARNING_STOCK_SUCCESS = "WARNING_STOCK_SUCCESS";
export const WARNING_STOCK_FAIL = "WARNING_STOCK_FAIL";

export const REVIEW_DETAILS_REQUEST = "REVIEW_DETAILS_REQUEST";
export const REVIEW_DETAILS_SUCCESS = "REVIEW_DETAILS_SUCCESS";
export const REVIEW_DETAILS_FAIL = "REVIEW_DETAILS_FAIL";

export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAIL = "UPDATE_REVIEW_FAIL";
export const UPDATE_REVIEW_RESET = "UPDATE_REVIEW_RESET";

// config
export const NEW_COLOR_REQUEST = "NEW_COLOR_REQUEST";
export const NEW_COLOR_SUCCESS = "NEW_COLOR_SUCCESS";
export const NEW_COLOR_FAIL = "NEW_COLOR_FAIL";
export const NEW_COLOR_RESET = "NEW_COLOR_RESET";

export const NEW_SIZE_REQUEST = "NEW_SIZE_REQUEST";
export const NEW_SIZE_SUCCESS = "NEW_SIZE_SUCCESS";
export const NEW_SIZE_FAIL = "NEW_SIZE_FAIL";
export const NEW_SIZE_RESET = "NEW_SIZE_RESET";

export const NEW_THICKNESS_REQUEST = "NEW_THICKNESS_REQUEST";
export const NEW_THICKNESS_SUCCESS = "NEW_THICKNESS_SUCCESS";
export const NEW_THICKNESS_FAIL = "NEW_THICKNESS_FAIL";
export const NEW_THICKNESS_RESET = "NEW_THICKNESS_RESET";

export const NEW_SUBCATEGORY_REQUEST = "NEW_SUBCATEGORY_REQUEST";
export const NEW_SUBCATEGORY_SUCCESS = "NEW_SUBCATEGORY_SUCCESS";
export const NEW_SUBCATEGORY_FAIL = "NEW_SUBCATEGORY_FAIL";
export const NEW_SUBCATEGORY_RESET = "NEW_SUBCATEGORY_RESET";

export const DELETE_COLOR_REQUEST = "DELETE_COLOR_REQUEST";
export const DELETE_COLOR_SUCCESS = "DELETE_COLOR_SUCCESS";
export const DELETE_COLOR_FAIL = "DELETE_COLOR_FAIL";
export const DELETE_COLOR_RESET = "DELETE_COLOR_RESET";

export const DELETE_SIZE_REQUEST = "DELETE_SIZE_REQUEST";
export const DELETE_SIZE_SUCCESS = "DELETE_SIZE_SUCCESS";
export const DELETE_SIZE_FAIL = "DELETE_SIZE_FAIL";
export const DELETE_SIZE_RESET = "DELETE_SIZE_RESET";

export const DELETE_THICKNESS_REQUEST = "DELETE_THICKNESS_REQUEST";
export const DELETE_THICKNESS_SUCCESS = "DELETE_THICKNESS_SUCCESS";
export const DELETE_THICKNESS_FAIL = "DELETE_THICKNESS_FAIL";
export const DELETE_THICKNESS_RESET = "DELETE_THICKNESS_RESET";

export const DELETE_SUBCATEGORY_REQUEST = "DELETE_SUBCATEGORY_REQUEST";
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS";
export const DELETE_SUBCATEGORY_FAIL = "DELETE_SUBCATEGORY_FAIL";
export const DELETE_SUBCATEGORY_RESET = "DELETE_SUBCATEGORY_RESET";

// config

// payment

export const INITIATE_PAYMENT_REQUEST = "INITIATE_PAYMENT_REQUEST";
export const INITIATE_PAYMENT_SUCCESS = "INITIATE_PAYMENT_SUCCESS";
export const INITIATE_PAYMENT_FAIL = "INITIATE_PAYMENT_FAIL";

// payment

export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";

export const REMOVE_PRODUCT_DETAILS = "REMOVE_PRODUCT_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";